name: Publish runbooks

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  run:
    runs-on: ubuntu-latest
    container:
      image: ministryofjustice/cloud-platform-tech-docs-publisher:1.3
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cd runbooks; bundle exec middleman build --build-dir docs
      env:
        GITHUB_PAGES_REPO_OWNER: ministryofjustice
        GITHUB_PAGES_REPO_AUTHOR: cloud-platform-moj
        GITHUB_PAGES_REPO_AUTHOR_EMAIL: platforms@digital.justice.gov.uk
        GITHUB_PAGES_REPO_NAME: cloud-platform-runbooks
        GITHUB_PAGES_RELEASE_BRANCH: gh-pages
        PROJECT_BUILD_FOLDER: docs
